name: task-management-system

services:
  task-db:
    image: postgres
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: task
      POSTGRES_DB: task
    ports:
      - "5432:5432"

  task-app:
    image: snamas/task-management
    depends_on:
      - task-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task-db:5432/task
      SPRING_DATASOURCE_USERNAME: task
      SPRING_DATASOURCE_PASSWORD: task

